### ISSUE TITLE
Aktivitäten in eigenes Modell auslagern?

### ISSUE THREAD

**Issue by noBlubb** [EmergencyX/Webapp#14]
Die Aktivitäten nachträglich zu erstellen ist komplizierter, denn Informationen wie "wer hat dieses Release erstellt" sind dann schwierig zu ermitteln. Andererseits ist es unter Umständen auch komplett irrelevant, wer Bilder hochlädt und wer genau ein Release freigegeben hat. Meinungen?

**Comment by ciajoe** [comment]
Wieso denn nachträglich?

**Comment by noBlubb** [comment]
Momentan werden die Aktivitäten zum Bilderupload nachträglich erstellt.
Wenn das Projekt angesehen wird, werden Bilder gefetcht und der Uploader
bestimmt (und alles für 10 Minuten in den Cache gelegt).

Damit muss aber zu jedem Upload der Uploader gespeichert werden und
entsprechend dann auch zu jeder weiteren Aktivität nachträglich der User
verfügbar sein. Das bläst aber die DB unnötig auf, wenn wir zu jedem
Repository den Ersteller etc speichern müssen.

Wenn wir das in eine eigene Tabelle legen (User, Aktivität, Timestamp),
generieren wir diesen Eintrag während des (z.B.) Uploads (und nicht während
die Projektseite geladen wird), haben trotzdem alle relevanten Infos parat
und müssen die eigentlichen Tabellen nicht aufblasen.

**Comment by ciajoe** [comment]
Ok. Das ist natürlich sinnvoll und usefull. :+1:

**Comment by noBlubb** [comment]
Erledigt :+1:
