### ISSUE TITLE
Registrierung implementieren

### ISSUE THREAD

**Issue by noBlubb** [EmergencyX/Webapp#15]
Registrierung mit
- Mail
- Username
- Passwort

implementieren.

**Comment by noBlubb** [comment]
Weder im Emergency Forum noch in der World of Emergency haben wir momentan einen Adapter.
Deshalb wird für 0.1 eine eigene Userverwaltung angestrebt.

**Comment by ciajoe** [comment]
Naja einen Adapter gäbe es theoretisch schon... um einfach nur user einzuloggen benötigt man kein richtiges Plugin, da tut es auch der Zugriff auf die user-Tabelle. Aber den zu bekommen, halte ich eher für unwahrscheinlich.

**Comment by noBlubb** [comment]
Ich habe in Bezug auf WCF / WBB 4 keine guten Alternativen finden können. 
Um 0.1 fertig zu  bekommen, würde ich deshalb nichts eigenes zu implementieren.

Die World of Emergency scheint ebenfalls das Laravel Framework zu verwenden, für 0.1 wird das aber ebenfalls nicht ohne weiteren Aufwand.

**Comment by ciajoe** [comment]
Warum hier und nicht auf GitLab?

**Comment by noBlubb** [comment]
Lol, keine Ahnung. Hab da mal ein Sync eingerichtet

**Comment by ciajoe** [comment]
Hm... Der scheint aber dort gar nicht vorhanden zu sein. :D

**Comment by noBlubb** [comment]
Ja, Seiteneffekt. Hab in einem Commit (der eben jetzt synchronisiert wurde) erwähnt, dass Ticket #15 geschlossen wurde - was hier eine andere ID ist, als in Gitlab :D
