### ISSUE TITLE
Einladung zu Gruppe

### ISSUE THREAD

**Issue by noBlubb** [EmergencyX/Webapp#9]
Hier kommen mir zwei Punkte in den Kopf:
- [ ] Limitierung von versendbaren Einladungen / Zeit
- [x] Einladungen sollten erst angenommen werden

Das gilt allgemein für alle Arten von Einladungen. Vielleicht implementieren wir an dieser Stelle eine Invitation-table, die alle Arten von Einladungen speichern kann.
- [x] InvitationController

**Comment by ciajoe** [comment]
Why limit the number of invitations?

**Comment by noBlubb** [comment]
Spam vermeiden eventuell

**Comment by ciajoe** [comment]
If the invitations are not send via user-specified text but via a "button" with default functions this should not be a huge problem. 
More interesting is somthing like "duplicate invitations". So if some one dismissed a invitation he should not get another invite.

**Comment by noBlubb** [comment]
Einladungen können jetzt ausgeschlagen werden. Wurde eine Einladung ausgeschlagen, wird sie in dieser Form nie wieder auftreten dürfen. Dieser "Bann" lässt sich aber auch wieder (wenn auch nur komplett) wieder aufheben. 
Eine ausgeschlagene Einladung kann nachträglich nicht mehr angenommen werden. Sie muss dann neu versendet werden. Verliert der Einladende seine Berechtigungen (-> kein Admin mehr in der Gruppe, zu der er eingeladen hatte), kann die Einladung nicht mehr verwendet werden um dieser Gruppe beizutreten. 
Zieht der Einladende seine Einladung zurück, wird das ebenfalls als "ausschlagen" gewertet. Sie kann nicht mehr angenommen werden und kann auch nicht mehr neu erstellt werden, bis der Eingeladene seine "Bann"-Liste zurücksetzt.

_Ich kann das Wort Invitation nicht mehr sehen._
